version: "3.9" # optional since v1.27.0

# mkdir -p ${PWD}/data/db/timescaledb
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# docker volume create beefy_grafana_data_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

x-importer: &importer

services:
  load-timescaledb:
    image: beefy-data-importer
    restart: always
    volumes:
      - data_directory:/data
    networks:
      - backend
    depends_on:
      - timescaledb
    environment:
      REDIS_URL: redis://redis:6379
      TIMESCALEDB_URL: postgres://beefy:beefy@timescaledb:5432/beefy
      LOG_LEVEL: "verbose"
      DATA_DIRECTORY: /data
      WORK_SCRIPT: ./dist/src/scripts/load-timescaledb.js
      WORK_CHAIN: all
      WORK_SOURCE: all

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 20G
        reservations:
          cpus: "0.25"
          memory: 5G
    environment:
      TZ: "UTC"
      POSTGRES_PORT: 5432
      POSTGRES_USER: beefy
      POSTGRES_PASSWORD: beefy
      POSTGRES_DB: beefy
      PGDATA: /home/postgres/pgdata/data
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 250M
    environment:
      TZ: UTC
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: grafana_ro
      POSTGRES_PASSWORD: grafana_ro
      POSTGRES_DB: beefy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/timescaledb.yml
    depends_on:
      - timescaledb
    networks:
      - backend

volumes:
  timescaledb_data:
    external: true
    name: beefy_timescaledb_data_directory
  grafana_data:
    external: true
    name: beefy_grafana_data_directory
  data_directory:
    external: true
    name: beefy_data_directory

networks:
  backend: {}
