version: "3.9" # optional since v1.27.0

# mkdir -p ${PWD}/data/db/timescaledb
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# mkdir -p ${PWD}/data/db/grafana && chmod 777 ${PWD}/data/db/grafana
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana --opt o=bind beefy_grafana_data_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - timescaledb_data:/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # configure the database
    #command: postgres -c max_locks_per_transaction=600
    env_file: ../../.env
    cpus: ${TIMESCALEDB_CPU_SHARE:-0.3}
    ports:
      - "5432:5432"
    environment:
      TZ: "UTC"
      POSTGRES_PORT: 5432
      POSTGRES_USER: beefy
      POSTGRES_PASSWORD: beefy
      POSTGRES_DB: beefy
      PGDATA: /pgdata
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - "3000:3000"
    env_file: ../../.env
    cpus: ${GRAFANA_CPU_SHARE:-0.3}
    environment:
      TZ: UTC
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: grafana_ro
      POSTGRES_PASSWORD: grafana_ro
      POSTGRES_DB: beefy
    volumes:
      - grafana_data_wtf:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/timescaledb.yml
    depends_on:
      - timescaledb
    networks:
      - backend

volumes:
  timescaledb_data:
    external: true
    name: beefy_timescaledb_data_directory
  grafana_data_wtf: {}
  grafana_data:
    external: true
    name: beefy_grafana_data_directory

networks:
  backend: {}
