version: "3.9" # optional since v1.27.0

# mkdir -p ${PWD}/data/db/timescaledb
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# mkdir -p ${PWD}/data/db/grafana && chmod 777 ${PWD}/data/db/grafana
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana --opt o=bind beefy_grafana_data_directory
# mkdir -p ${PWD}/data/db/grafana_plugins && chmod 777 ${PWD}/data/db/grafana_plugins
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana_plugins --opt o=bind beefy_grafana_plugins_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

services:
  grafana:
    image: grafana/grafana:10.1.4
    ports:
      - "3000:3000"
    env_file: ../.env-grafana
    cpus: ${GRAFANA_CPU_SHARE:-0.3}
    stop_signal: SIGINT
    environment:
      TZ: UTC
      POSTGRES_HOST: ${GRAFANA_POSTGRES_HOST}
      POSTGRES_PORT: ${GRAFANA_POSTGRES_PORT}
      POSTGRES_USER: ${GRAFANA_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GRAFANA_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GRAFANA_POSTGRES_DB}
      PORT: 3000
      GRAFANA_WEBAPP_DOMAIN_NAME: localhost
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
      GF_AUTH_DISABLE_LOGIN: false
      GF_AUTH_DISABLE_LOGIN_FORM: false
      GF_AUTH_GITHUB_ENABLED: false
      DISCORD_ALERT_WEBHOOK_URL: "http://localhost"
    volumes:
      - grafana_data_wtf:/var/lib/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - ./analytics/custom.ini:/etc/grafana/grafana.ini
      - ./analytics/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./analytics/provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./analytics/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - backend

volumes:
  grafana_data_wtf: {}
  grafana_data:
    external: true
    name: beefy_grafana_data_directory
  grafana_plugins:
    external: true
    name: beefy_grafana_plugins_directory

networks:
  backend: {}
