version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/git-work --opt o=bind beefy_git_work_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana --opt o=bind beefy_grafana_data_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

# docker compose -f deploy/docker-compose.yml up -d
# docker compose -f deploy/docker-compose.yml logs -f
# docker compose -f deploy/docker-compose.yml down
# docker compose -f deploy/docker-compose.yml rm # cleanup logs sometimes

# docker compose -f deploy/docker-compose.yml logs -f importer

# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker compose -f deploy/docker-compose.yml stop importer-products importer-investment-historical importer-investment-recent importer-prices-historical importer-prices-recent importer-share-rates-historical
# docker compose -f deploy/docker-compose.yml up importer-products importer-investment-historical importer-investment-recent importer-prices-historical importer-prices-recent importer-share-rates-historical -d --force-recreate
# docker compose -f deploy/docker-compose.yml logs -f importer-products importer-investment-historical importer-investment-recent importer-prices-historical importer-prices-recent importer-share-rates-historical

# RUN a command
# docker exec -it -e LOG_LEVEL=trace deploy-importer-investment-historical-1 node ./dist/src/script/run.js beefy:run -i historical -c kava
# docker exec -it -e LOG_LEVEL=trace deploy-importer-products-1 node ./dist/src/script/run.js db:migrate

# BACKUP
# cd ~/beefy/snapshots
# docker stop deploy-importer-1 deploy-grafana-1 deploy-redis-1
# docker run --rm -it --network container:deploy-timescaledb-1 -w /data -v $PWD:/data beefy-data-importer /bin/sh
# apk add postgresql-client
# pg_dump -h timescaledb -p 5432 -U beefy -Fc -v -f beefy.`date +'%Y-%m-%d.%H-%M-%S'`.pg_dump.bak beefy

x-importer: &importer
  image: beefy-data-importer
  restart: always
  env_file: ../.env
  environment:
    WORK_CMD: "./dist/src/script/run.js beefy:run -t products -r 1day"
  volumes:
    - git_work_directory:/git_work
  networks:
    - backend
  depends_on:
    - redis
    - timescaledb

x-importer-env: &importer-env
  REDIS_URL: redis://redis:6379
  TIMESCALEDB_URL: postgres://beefy:beefy@timescaledb:5432/beefy
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work

volumes:
  git_work_directory:
    external: true
    name: beefy_git_work_directory
  timescaledb_data:
    external: true
    name: beefy_timescaledb_data_directory
  grafana_data:
    external: true
    name: beefy_grafana_data_directory

networks:
  backend: {}

services:
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no --replicaof no one
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb-ha:pg14.4-ts2.7.2-latest
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=250'
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 20G
        reservations:
          cpus: "0.25"
          memory: 5G
    environment:
      TZ: "UTC"
      POSTGRES_PORT: 5432
      POSTGRES_USER: beefy
      POSTGRES_PASSWORD: beefy
      POSTGRES_DB: beefy
      PGDATA: /home/postgres/pgdata/data
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 250M
    environment:
      TZ: UTC
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: grafana_ro
      POSTGRES_PASSWORD: grafana_ro
      POSTGRES_DB: beefy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./db/grafana.ini:/etc/grafana/grafana.ini
      - ./db/grafana_datasource.yml:/etc/grafana/provisioning/datasources/timescaledb.yml
    depends_on:
      - timescaledb
    networks:
      - backend

  importer-products:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t products -r 1day"

  importer-investment-historical-bsc:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c bsc -r 15sec"

  importer-investment-historical-fantom:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c fantom -r 15sec"

  importer-investment-historical-avax:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c avax -r 15sec"

  importer-investment-historical-polygon:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c polygon -r 15sec"

  importer-investment-historical-other-1:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c arbitrum -c aurora -c emerald -c fuse -c harmony -c metis -c optimism -c kava -r 15sec"

  importer-investment-historical-other-2:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c celo -c cronos -c heco -c moonriver -r 15sec"

  importer-investment-historical-moonbeam:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c moonbeam -r 15sec -e"

  importer-investment-recent:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c all -r 15min"

  importer-prices-historical:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-prices -c all -r 1hour"

  importer-prices-recent:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent-prices -c all -r 15min"

  importer-share-rates-historical:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c all -r 1hour"
