version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/git-work --opt o=bind beefy_git_work_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana --opt o=bind beefy_grafana_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana_plugins --opt o=bind beefy_grafana_plugins_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

# docker compose -f deploy/docker-compose.yml up -d
# docker compose -f deploy/docker-compose.yml logs -f
# docker compose -f deploy/docker-compose.yml down
# docker compose -f deploy/docker-compose.yml rm # cleanup logs sometimes

# docker compose -f deploy/docker-compose.yml logs -f importer

# export TASK_LIST="importer-products importer-prices-historical importer-prices-recent importer-reward-snapshots importer-investment-recent-arbitrum importer-investment-recent-aurora importer-investment-recent-avax importer-investment-recent-bsc importer-investment-recent-celo importer-investment-recent-cronos importer-investment-recent-ethereum importer-investment-recent-emerald importer-investment-recent-fantom importer-investment-recent-fuse importer-investment-recent-harmony importer-investment-recent-heco importer-investment-recent-kava importer-investment-recent-metis importer-investment-recent-moonbeam importer-investment-recent-moonriver importer-investment-recent-optimism importer-investment-recent-polygon importer-investment-recent-syscoin importer-investment-historical-bsc-before-2022 importer-investment-historical-arbitrum importer-investment-historical-aurora importer-investment-historical-avax importer-investment-historical-bsc importer-investment-historical-celo importer-investment-historical-cronos importer-investment-historical-ethereum importer-investment-historical-emerald importer-investment-historical-fantom importer-investment-historical-fuse importer-investment-historical-harmony importer-investment-historical-heco importer-investment-historical-kava importer-investment-historical-metis importer-investment-historical-moonbeam importer-investment-historical-moonriver importer-investment-historical-optimism importer-investment-historical-polygon importer-investment-historical-syscoin importer-investment-historical-share-rate-arbitrum importer-investment-historical-share-rate-aurora importer-investment-historical-share-rate-avax importer-investment-historical-share-rate-bsc importer-investment-historical-share-rate-celo importer-investment-historical-share-rate-cronos importer-investment-historical-share-rate-ethereum importer-investment-historical-share-rate-emerald importer-investment-historical-share-rate-fantom importer-investment-historical-share-rate-fuse importer-investment-historical-share-rate-harmony importer-investment-historical-share-rate-heco importer-investment-historical-share-rate-kava importer-investment-historical-share-rate-metis importer-investment-historical-share-rate-moonbeam importer-investment-historical-share-rate-moonriver importer-investment-historical-share-rate-optimism importer-investment-historical-share-rate-polygon importer-investment-historical-share-rate-syscoin"
# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker compose -f deploy/docker-compose.yml stop $TASK_LIST
# docker compose -f deploy/docker-compose.yml up $TASK_LIST -d --force-recreate
# docker compose -f deploy/docker-compose.yml logs -f $TASK_LIST
# docker compose -f deploy/docker-compose.yml logs -f $TASK_LIST | grep -vi 'archive node' | grep -vi 'missing revert data in call' | grep -vi 'missing trie node' | grep -vi 'The operation was unable to achieve a quorum during its retry window' | grep -vi 'Connection timeout error, will retry'

# docker compose -f deploy/docker-compose.yml up public-api -d --force-recreate
# RUN a command
# docker exec -it -e LOG_LEVEL=trace deploy-importer-investment-historical-1 node ./dist/src/script/run.js beefy:run -i historical -c kava
# docker exec -it -e LOG_LEVEL=trace deploy-importer-products-1 node ./dist/src/script/run.js db:migrate

x-importer: &importer
  image: beefy-data-importer
  restart: always
  env_file: ../.env
  environment:
    WORK_CMD: "./dist/src/script/run.js beefy:run -t products -l 1day"
  volumes:
    - git_work_directory:/git_work
  networks:
    - backend
  depends_on:
    - redis
    - timescaledb

x-importer-env: &importer-env
  REDIS_URL: redis://redis:6379
  TIMESCALEDB_URL: postgres://beefy:beefy@timescaledb:5432/beefy
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work

volumes:
  git_work_directory:
    external: true
    name: beefy_git_work_directory
  timescaledb_data:
    external: true
    name: beefy_timescaledb_data_directory
  grafana_data:
    external: true
    name: beefy_grafana_data_directory
  grafana_plugins:
    external: true
    name: beefy_grafana_plugins_directory

networks:
  backend: {}

services:
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no --replicaof no one
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb-ha:pg14.4-ts2.7.2-latest
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=250' -c logging_collector=off -c log_min_duration_statement=10s -c log_statement=none
    shm_size: 256M
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 20G
        reservations:
          cpus: "0.25"
          memory: 5G
    environment:
      TZ: "UTC"
      POSTGRES_PORT: 5432
      POSTGRES_USER: beefy
      POSTGRES_PASSWORD: beefy
      POSTGRES_DB: beefy
      PGDATA: /home/postgres/pgdata/data
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.2.3
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 250M
    environment:
      TZ: UTC
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: grafana_ro
      POSTGRES_PASSWORD: grafana_ro
      POSTGRES_DB: beefy
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - ./db/grafana.ini:/etc/grafana/grafana.ini
      - ./db/grafana_datasource.yml:/etc/grafana/provisioning/datasources/timescaledb.yml
    depends_on:
      - timescaledb
    networks:
      - backend

  public-api:
    image: beefy-data-importer
    restart: always
    env_file: ../.env
    ports:
      - "8080:8080"
    environment:
      TZ: UTC
      REDIS_URL: redis://redis:6379
      TIMESCALEDB_URL: postgres://api_ro:api_ro@timescaledb:5432/beefy
      API_LISTEN: "::" # listen on all interfaces inside the container
      WORK_CMD: "./dist/src/api/api.js"
    networks:
      - backend
    depends_on:
      - redis
      - timescaledb

  importer-products:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t products -l 1day"

  importer-prices-historical:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-prices -c all -l 1hour"

  importer-prices-recent:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent-prices -c all -l 15min"

  importer-reward-snapshots:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t reward-snapshots -c all -l 4hour"

  # arbitrum aurora avax bsc celo cronos ethereum emerald fantom fuse harmony heco kava metis moonbeam moonriver optimism polygon syscoin

  importer-investment-recent-arbitrum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c arbitrum  -l 15min"

  importer-investment-recent-aurora:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c aurora  -l 15min"

  importer-investment-recent-avax:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c avax  -l 15min"

  importer-investment-recent-bsc:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c bsc  -l 15min"

  importer-investment-recent-celo:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c celo  -l 15min"

  importer-investment-recent-cronos:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c cronos  -l 15min"

  importer-investment-recent-ethereum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c ethereum  -l 15min"

  importer-investment-recent-emerald:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c emerald  -l 15min"

  importer-investment-recent-fantom:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c fantom  -l 15min"

  importer-investment-recent-fuse:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c fuse  -l 15min"

  importer-investment-recent-harmony:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c harmony  -l 15min"

  importer-investment-recent-heco:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c heco  -l 15min"

  importer-investment-recent-kava:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c kava  -l 15min"

  importer-investment-recent-metis:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c metis  -l 15min"

  importer-investment-recent-moonbeam:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c moonbeam  -l 15min"

  importer-investment-recent-moonriver:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c moonriver  -l 15min"

  importer-investment-recent-optimism:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c optimism  -l 15min"

  importer-investment-recent-polygon:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c polygon  -l 15min"

  importer-investment-recent-syscoin:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c syscoin  -l 15min"

  # arbitrum aurora avax bsc celo cronos ethereum emerald fantom fuse harmony heco kava metis moonbeam moonriver optimism polygon syscoin

  importer-investment-historical-bsc-before-2022:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c bsc --forceRpcUrl https://bsc-mainnet.nodereal.io/v1/<RPC_API_KEY_NODEREAL_2> -l 15sec"

  importer-investment-historical-arbitrum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c arbitrum -l 15min"

  importer-investment-historical-aurora:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c aurora -l 15min"

  importer-investment-historical-avax:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c avax -l 15sec"

  importer-investment-historical-bsc:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c bsc -l 15sec"

  importer-investment-historical-celo:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c cronos -l 15sec"

  importer-investment-historical-cronos:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c cronos -l 15min"

  importer-investment-historical-ethereum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c ethereum -l 15min"

  importer-investment-historical-emerald:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c emerald -l 15min"

  importer-investment-historical-fantom:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c fantom -l 15sec"

  importer-investment-historical-fuse:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c fuse -l 15min"

  importer-investment-historical-harmony:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c harmony -l 15min"

  importer-investment-historical-heco:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c heco -l 15sec"

  importer-investment-historical-kava:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c kava -l 15sec"

  importer-investment-historical-metis:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c metis -l 15min"

  importer-investment-historical-moonbeam:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c moonbeam -l 15sec"

  importer-investment-historical-moonriver:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c moonriver -l 15sec"

  importer-investment-historical-optimism:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c optimism -l 15sec"

  importer-investment-historical-polygon:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c polygon -l 15sec"

  importer-investment-historical-syscoin:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c syscoin -l 15min"

  # arbitrum aurora avax bsc celo cronos ethereum emerald fantom fuse harmony heco kava metis moonbeam moonriver optimism polygon syscoin

  importer-investment-historical-share-rate-arbitrum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c arbitrum -l 15min"

  importer-investment-historical-share-rate-aurora:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c aurora -l 15min"

  importer-investment-historical-share-rate-avax:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c avax -l 15sec"

  importer-investment-historical-share-rate-bsc:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c bsc -l 15sec"

  importer-investment-historical-share-rate-celo:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c cronos -l 15sec"

  importer-investment-historical-share-rate-cronos:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c cronos -l 15min"

  importer-investment-historical-share-rate-ethereum:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c ethereum -l 15min"

  importer-investment-historical-share-rate-emerald:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c emerald -l 15min"

  importer-investment-historical-share-rate-fantom:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c fantom -l 15sec"

  importer-investment-historical-share-rate-fuse:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c fuse -l 15min"

  importer-investment-historical-share-rate-harmony:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c harmony -l 15min"

  importer-investment-historical-share-rate-heco:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c heco -l 15sec"

  importer-investment-historical-share-rate-kava:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c kava -l 15sec"

  importer-investment-historical-share-rate-metis:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c metis -l 15min"

  importer-investment-historical-share-rate-moonbeam:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c moonbeam -l 15sec"

  importer-investment-historical-share-rate-moonriver:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c moonriver -l 15sec"

  importer-investment-historical-share-rate-optimism:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c optimism -l 15sec"

  importer-investment-historical-share-rate-polygon:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c polygon -l 15sec"

  importer-investment-historical-share-rate-syscoin:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c syscoin -l 15min"
