version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/indexed --opt o=bind beefy_data_directory
# docker compose -p beefy -f deploy/docker-compose.yml up -d
# docker compose -p beefy -f deploy/docker-compose.yml logs -f
# docker compose -p beefy -f deploy/docker-compose.yml down
# docker compose -p beefy -f deploy/docker-compose.yml rm # cleanup logs sometimes

x-importer: &importer
  image: beefy-data-importer
  restart: always
  command:
    [
      "npx",
      "ts-node",
      "$$WORK_SCRIPT",
      "--chain",
      "$$WORK_CHAIN",
      "--source",
      $$WORK_SOURCE,
    ]
  volumes:
    - data_directory:/data
  networks:
    - backend
  depends_on:
    - redis

x-vault-importer-env: &vault-importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "info"
  DATA_DIRECTORY: /data
  WORK_SCRIPT: ./src/import/import-vault-transfers.ts

x-block-samples-importer-env: &block-samples-importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "info"
  DATA_DIRECTORY: /data
  WORK_SCRIPT: ./src/import/import-block-samples.ts

x-ppfs-importer-env: &ppfs-importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "info"
  DATA_DIRECTORY: /data
  WORK_SCRIPT: ./src/import/import-vault-ppfs.ts

services:
  #############################################################################
  #############################################################################
  #############################################################################

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  #############################################################################
  #############################################################################
  #############################################################################

  import-vault-transfers-fantom:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: fantom
      WORK_SOURCE: explorer

  import-vault-transfers-cronos:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: cronos
      WORK_SOURCE: explorer

  import-vault-transfers-bsc:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: bsc
      WORK_SOURCE: explorer

  import-vault-transfers-polygon:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: polygon
      WORK_SOURCE: explorer

  import-vault-transfers-heco:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: heco
      WORK_SOURCE: explorer

  import-vault-transfers-avax:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: avax
      WORK_SOURCE: explorer

  import-vault-transfers-moonbeam:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: moonbeam
      WORK_SOURCE: explorer

  import-vault-transfers-celo:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: celo
      WORK_SOURCE: explorer

  import-vault-transfers-moonriver:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: moonriver
      WORK_SOURCE: explorer

  import-vault-transfers-arbitrum:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: arbitrum
      WORK_SOURCE: explorer

  import-vault-transfers-aurora:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: aurora
      WORK_SOURCE: explorer

  # disabled because explorer api is different
  #import-vault-transfers-metis:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: metis
  #    WORK_SOURCE: rpc

  # disabled because explorer api is different
  #import-vault-transfers-harmony:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: harmony
  #    WORK_SOURCE: rpc

  import-vault-transfers-fuse:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: fuse
      WORK_SOURCE: rpc # explorer requires toBlock to be set

  # no beefy vault list for now
  #import-vault-transfers-syscoin:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: syscoin

  # disabled because explorer api is different
  #import-vault-transfers-emerald:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: emerald
  #    WORK_SOURCE: rpc

  #############################################################################
  #############################################################################
  #############################################################################

  import-block-samples-fantom:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: fantom

  import-block-samples-cronos:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: cronos

  import-block-samples-bsc:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: bsc

  import-block-samples-polygon:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: polygon

  import-block-samples-heco:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: heco

  import-block-samples-avax:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: avax

  import-block-samples-moonbeam:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: moonbeam

  # disabled because script needs to be adapted
  #import-block-samples-celo:
  #  <<: *importer
  #  environment:
  #    <<: *block-samples-importer-env
  #    WORK_CHAIN: celo

  import-block-samples-moonriver:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: moonriver

  import-block-samples-arbitrum:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: arbitrum

  import-block-samples-aurora:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: aurora

  import-block-samples-metis:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: metis

  import-block-samples-harmony:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: harmony

  import-block-samples-fuse:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: fuse

  import-block-samples-syscoin:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: syscoin

  import-block-samples-emerald:
    <<: *importer
    environment:
      <<: *block-samples-importer-env
      WORK_CHAIN: emerald

  #############################################################################
  #############################################################################
  #############################################################################

  import-vault-ppfs-fantom:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: fantom

  import-vault-ppfs-cronos:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: cronos

  import-vault-ppfs-bsc:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: bsc

  import-vault-ppfs-polygon:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: polygon

  import-vault-ppfs-heco:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: heco

  import-vault-ppfs-avax:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: avax

  import-vault-ppfs-moonbeam:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: moonbeam

  # disabled because block script is disabled for celo
  #import-vault-ppfs-celo:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: celo

  import-vault-ppfs-moonriver:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: moonriver

  import-vault-ppfs-arbitrum:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: arbitrum

  import-vault-ppfs-aurora:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: aurora

  # disabled because explorer api is different
  #import-vault-ppfs-metis:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: metis

  # disabled because explorer api is different
  #import-vault-ppfs-harmony:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: harmony

  import-vault-ppfs-fuse:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: fuse

  # no beefy vault list for now
  #import-vault-ppfs-syscoin:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: syscoin

  # disabled because explorer api is different
  #import-vault-ppfs-emerald:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: emerald

volumes:
  data_directory:
    external: true
    name: beefy_data_directory

networks:
  frontend: {}
  backend: {}
