version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/git-work --opt o=bind beefy_git_work_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/timescaledb --opt o=bind beefy_timescaledb_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana --opt o=bind beefy_grafana_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/db/grafana_plugins --opt o=bind beefy_grafana_plugins_directory

# tune the system: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool
# docker exec -it beefy_db-timescaledb-1 timescaledb-tune --yes --memory="4GB" --cpus=2 --max-bg-workers=16 --dry-run

# docker compose -f deploy/docker-compose.yml up -d
# docker compose -f deploy/docker-compose.yml logs -f
# docker compose -f deploy/docker-compose.yml down
# docker compose -f deploy/docker-compose.yml rm # cleanup logs sometimes

# docker compose -f deploy/docker-compose.yml logs -f importer

# export TASK_LIST="importer-products importer-investment-recent importer-prices-historical importer-prices-recent importer-investment-historical-bsc-unfinished importer-investment-historical-small-unfinished importer-investment-historical-fully-loaded importer-share-rates-historical-bsc-unfinished importer-share-rates-historical-small-unfinished importer-share-rates-historical-fully-loaded"
# docker build -t beefy-data-importer -f ./deploy/import/Dockerfile ./
# docker compose -f deploy/docker-compose.yml stop $TASK_LIST
# docker compose -f deploy/docker-compose.yml up $TASK_LIST -d --force-recreate
# docker compose -f deploy/docker-compose.yml logs -f $TASK_LIST
# docker compose -f deploy/docker-compose.yml logs -f $TASK_LIST | grep -vi 'archive node' | grep -vi 'missing revert data in call' | grep -vi 'missing trie node' | grep -vi 'The operation was unable to achieve a quorum during its retry window' | grep -vi 'Connection timeout error, will retry'

# docker compose -f deploy/docker-compose.yml up public-api -d --force-recreate
# RUN a command
# docker exec -it -e LOG_LEVEL=trace deploy-importer-investment-historical-1 node ./dist/src/script/run.js beefy:run -i historical -c kava
# docker exec -it -e LOG_LEVEL=trace deploy-importer-products-1 node ./dist/src/script/run.js db:migrate

x-importer: &importer
  image: beefy-data-importer
  restart: always
  env_file: ../.env
  environment:
    WORK_CMD: "./dist/src/script/run.js beefy:run -t products -l 1day"
  volumes:
    - git_work_directory:/git_work
  networks:
    - backend
  depends_on:
    - redis
    - timescaledb

x-importer-env: &importer-env
  REDIS_URL: redis://redis:6379
  TIMESCALEDB_URL: postgres://beefy:beefy@timescaledb:5432/beefy
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work

volumes:
  git_work_directory:
    external: true
    name: beefy_git_work_directory
  timescaledb_data:
    external: true
    name: beefy_timescaledb_data_directory
  grafana_data:
    external: true
    name: beefy_grafana_data_directory
  grafana_plugins:
    external: true
    name: beefy_grafana_plugins_directory

networks:
  backend: {}

services:
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no --replicaof no one
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb-ha:pg14.4-ts2.7.2-latest
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=250'
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 20G
        reservations:
          cpus: "0.25"
          memory: 5G
    environment:
      TZ: "UTC"
      POSTGRES_PORT: 5432
      POSTGRES_USER: beefy
      POSTGRES_PASSWORD: beefy
      POSTGRES_DB: beefy
      PGDATA: /home/postgres/pgdata/data
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.2.3
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 1G
        reservations:
          cpus: "0.05"
          memory: 250M
    environment:
      TZ: UTC
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: grafana_ro
      POSTGRES_PASSWORD: grafana_ro
      POSTGRES_DB: beefy
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - ./db/grafana.ini:/etc/grafana/grafana.ini
      - ./db/grafana_datasource.yml:/etc/grafana/provisioning/datasources/timescaledb.yml
    depends_on:
      - timescaledb
    networks:
      - backend

  public-api:
    image: beefy-data-importer
    restart: always
    env_file: ../.env
    ports:
      - "8080:8080"
    environment:
      TZ: UTC
      REDIS_URL: redis://redis:6379
      TIMESCALEDB_URL: postgres://api_ro:api_ro@timescaledb:5432/beefy
      API_LISTEN: "::" # listen on all interfaces inside the container
      WORK_CMD: "./dist/src/api/api.js"
    networks:
      - backend
    depends_on:
      - redis
      - timescaledb

  importer-products:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t products -l 1day"

  importer-investment-recent:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent -c all -l 15min"

  importer-prices-historical:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-prices -c all -l 1hour"

  importer-prices-recent:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t recent-prices -c all -l 15min"

  # arbitrum aurora avax bsc celo cronos ethereum emerald fantom fuse harmony heco kava metis moonbeam moonriver optimism polygon syscoin

  importer-investment-historical-bsc-unfinished:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c bsc -r 8 -l 15sec"

  importer-investment-historical-small-unfinished:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c celo cronos heco moonriver -l 15sec"

  importer-investment-historical-fully-loaded:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical -c arbitrum aurora avax ethereum emerald fantom fuse harmony kava metis moonbeam optimism polygon syscoin -l 15min"

  # arbitrum aurora avax bsc celo cronos ethereum emerald fantom fuse harmony heco kava metis moonbeam moonriver optimism polygon syscoin

  importer-share-rates-historical-bsc-unfinished:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c bsc -l 15sec"

  importer-share-rates-historical-small-unfinished:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c arbitrum celo cronos heco kava moonbeam moonriver -l 15sec"

  importer-share-rates-historical-fully-loaded:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_CMD: "./dist/src/script/run.js beefy:run -t historical-share-rate -c aurora avax ethereum emerald fantom fuse harmony metis optimism polygon syscoin -l 15min"
