version: "3.9" # optional since v1.27.0

services:
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    command: redis-server --save "" --appendonly no --maxmemory 314572800 --replicaof no one
    ports:
      - "6379:6379"
