version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/indexed --opt o=bind beefy_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/git-work --opt o=bind beefy_git_work_directory
# docker compose -p beefy -f deploy/docker-compose.yml up -d
# docker compose -p beefy -f deploy/docker-compose.yml logs -f
# docker compose -p beefy -f deploy/docker-compose.yml down
# docker compose -p beefy -f deploy/docker-compose.yml rm # cleanup logs sometimes

x-importer: &importer
  image: beefy-data-importer
  restart: always
  env_file: ../../.env
  volumes:
    - data_directory:/data
    - git_work_directory:/git_work
  networks:
    - backend
  depends_on:
    - redis

x-importer-env: &importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "error"
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work
  WORK_CHAIN: all

volumes:
  data_directory:
    external: true
    name: beefy_data_directory
  git_work_directory:
    external: true
    name: beefy_git_work_directory

networks:
  backend: {}

services:
  ######################### Infra ##################################

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no --replicaof no one
    networks:
      - backend

  ######################### Basic Data ##################################

  import-block-samples:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-block-samples.js

  import-oracle-prices:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-prices.js

  ######################### Vault Data ##################################

  import-vault-transfers:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-vault-transfers.js

  import-vault-ppfs:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-vault-ppfs.js

  ######################### Strategy/Fee Data ##################################

  import-vault-strategies:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-vault-strategies.js

  import-native-transfers-from-strategies:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-strategies-native-transfer-from.js

  import-strategy-fee-recipients:
    <<: *importer
    environment:
      <<: *importer-env
      WORK_SCRIPT: ./dist/src/import/import-strategies-fee-recipients.js
