version: "3.9" # optional since v1.27.0

# docker build -t beefy-data-importer -f ./deploy/Dockerfile ./
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/indexed --opt o=bind beefy_data_directory
# docker volume create --driver local --opt type=none --opt device=${PWD}/data/git-work --opt o=bind beefy_git_work_directory
# docker compose -p beefy -f deploy/docker-compose.yml up -d
# docker compose -p beefy -f deploy/docker-compose.yml logs -f
# docker compose -p beefy -f deploy/docker-compose.yml down
# docker compose -p beefy -f deploy/docker-compose.yml rm # cleanup logs sometimes

x-importer: &importer
  image: beefy-data-importer
  restart: always
  env_file: ../../.env
  volumes:
    - data_directory:/data
    - git_work_directory:/git_work
  networks:
    - backend
  depends_on:
    - redis

x-vault-importer-env: &vault-importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "info"
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work
  WORK_SCRIPT: ./dist/src/import/import-vault-transfers.js

x-ppfs-importer-env: &ppfs-importer-env
  REDIS_URL: redis://redis:6379
  LOG_LEVEL: "info"
  DATA_DIRECTORY: /data
  GIT_WORK_DIRECTORY: /git_work
  WORK_SCRIPT: ./dist/src/import/import-vault-ppfs.js

volumes:
  data_directory:
    external: true
    name: beefy_data_directory
  git_work_directory:
    external: true
    name: beefy_git_work_directory

networks:
  backend: {}

services:
  #############################################################################
  #############################################################################
  #############################################################################

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no --replicaof no one
    networks:
      - backend

  #############################################################################
  #############################################################################
  #############################################################################

  import-vault-strategies-all-chains:
    <<: *importer
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: "info"
      DATA_DIRECTORY: /data
      GIT_WORK_DIRECTORY: /git_work
      WORK_SCRIPT: ./dist/src/import/import-vault-strategies.js
      WORK_CHAIN: all
      WORK_SOURCE: all

  #############################################################################
  #############################################################################
  #############################################################################

  import-block-samples-all-chains:
    <<: *importer
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: "info"
      DATA_DIRECTORY: /data
      GIT_WORK_DIRECTORY: /git_work
      WORK_SCRIPT: ./dist/src/import/import-block-samples.js
      WORK_CHAIN: all

  #############################################################################
  #############################################################################
  #############################################################################

  import-native-transfers-from-strategies:
    <<: *importer
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: "info"
      DATA_DIRECTORY: /data
      GIT_WORK_DIRECTORY: /git_work
      WORK_SCRIPT: ./dist/src/import/import-strategies-native-transfer-from.js
      WORK_CHAIN: all
      WORK_SOURCE: all

  #############################################################################
  #############################################################################
  #############################################################################

  import-oracle-prices:
    <<: *importer
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: "info"
      DATA_DIRECTORY: /data
      GIT_WORK_DIRECTORY: /git_work
      WORK_SCRIPT: ./dist/src/import/import-prices.js
      WORK_CHAIN: all
      WORK_SOURCE: all

  #############################################################################
  #############################################################################
  #############################################################################

  import-strategy-fee-recipients:
    <<: *importer
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: "info"
      DATA_DIRECTORY: /data
      GIT_WORK_DIRECTORY: /git_work
      WORK_SCRIPT: ./dist/src/import/import-strategies-fee-recipients.js
      WORK_CHAIN: all
      WORK_SOURCE: all

  #############################################################################
  #############################################################################
  #############################################################################

  import-vault-transfers-fantom:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: fantom
      WORK_SOURCE: explorer

  import-vault-transfers-cronos:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: cronos
      WORK_SOURCE: rpc # cf. eplain in config

  import-vault-transfers-bsc:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: bsc
      WORK_SOURCE: explorer

  import-vault-transfers-polygon:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: polygon
      WORK_SOURCE: explorer

  import-vault-transfers-heco:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: heco
      WORK_SOURCE: explorer

  import-vault-transfers-avax:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: avax
      WORK_SOURCE: explorer

  import-vault-transfers-moonbeam:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: moonbeam
      WORK_SOURCE: explorer

  import-vault-transfers-celo:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: celo
      WORK_SOURCE: explorer

  import-vault-transfers-moonriver:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: moonriver
      WORK_SOURCE: explorer

  import-vault-transfers-arbitrum:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: arbitrum
      WORK_SOURCE: explorer

  import-vault-transfers-aurora:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: aurora
      WORK_SOURCE: rpc # cf. eplain in config

  import-vault-transfers-metis:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: metis
      WORK_SOURCE: explorer

  import-vault-transfers-harmony:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: harmony
      WORK_SOURCE: rpc # no ethscan-compatible for harmony yet

  import-vault-transfers-optimism:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: optimism
      WORK_SOURCE: explorer

  import-vault-transfers-fuse:
    <<: *importer
    environment:
      <<: *vault-importer-env
      WORK_CHAIN: fuse
      WORK_SOURCE: rpc # explorer requires toBlock to be set

  # no beefy vault list for now
  #import-vault-transfers-syscoin:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: syscoin
  #    WORK_SOURCE: ???

  # disabled because explorer api is different
  #import-vault-transfers-emerald:
  #  <<: *importer
  #  environment:
  #    <<: *vault-importer-env
  #    WORK_CHAIN: emerald
  #    WORK_SOURCE: rpc

  #############################################################################
  #############################################################################
  #############################################################################

  import-vault-ppfs-fantom:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: fantom

  import-vault-ppfs-cronos:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: cronos

  import-vault-ppfs-bsc:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: bsc

  import-vault-ppfs-polygon:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: polygon

  import-vault-ppfs-heco:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: heco

  import-vault-ppfs-avax:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: avax

  import-vault-ppfs-moonbeam:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: moonbeam

  import-vault-ppfs-celo:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: celo

  import-vault-ppfs-moonriver:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: moonriver

  import-vault-ppfs-arbitrum:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: arbitrum

  import-vault-ppfs-aurora:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: aurora

  import-vault-ppfs-metis:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: metis

  import-vault-ppfs-harmony:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: harmony

  import-vault-ppfs-fuse:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: fuse

  import-vault-ppfs-optimism:
    <<: *importer
    environment:
      <<: *ppfs-importer-env
      WORK_CHAIN: optimism

  # no beefy vault list for now
  #import-vault-ppfs-syscoin:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: syscoin

  # disabled because explorer api is different
  #import-vault-ppfs-emerald:
  #  <<: *importer
  #  environment:
  #    <<: *ppfs-importer-env
  #    WORK_CHAIN: emerald
